###
GET http://localhost:5000/api/client/clientAll

###
POST https://ztechnology.up.railway.app/api/client/createClient
Content-Type: application/json

{
    "name": "sebastian figueroa",
    "email": "sebastian@figueroa.com",
    "phone" : "399789",
    "id_user" : 8
    
}