### consultar producto
GET ztechnology.up.railway.app/api/product/consultar-productos

###guardar producto
POST ztechnology.up.railway.app/api/product/guardar-producto
Content-Type: application/json

{
    "name": "iPhone 15 pro max",
    "description": "Smartphone de Apple con 256GB de almacenamiento",
    "price": "1300"
}

### actualizar producto
PUT ztechnology.up.railway.app/api/product/actualizar-producto
Content-Type: application/json

{
    "id_product" : 11,
    "name": "iPhone 15 pro max",
    "description": "Smartphone de Apple con 256GB de almacenamiento",
    "price": "1200"
}

### Eliminar product0
DELETE ztechnology.up.railway.app/api/product/eleminar-producto/11